### ISSUE TITLE
The class 'PropertyChangeNotifier' can't be used as a mixin because it extends a class other than Object. dart(mixin_inherits_from_not_object)

### ISSUE THREAD

**Issue by nosmirck** [VGVentures/property_change_notifier#10]
Trying the example code on a brand new app with latest Stable release gives the following error:

`The class 'PropertyChangeNotifier' can't be used as a mixin because it extends a class other than Object. dart(mixin_inherits_from_not_object)`

However, extending (instead of mixin the class) works fine with the model.

Was this changed? is the documentation wrong? why is this happening?

**Comment by abhip167** [comment]
Same Problem here tooo

**Comment by martinrybak** [comment]
Hi there, please see the readme: https://github.com/VGVentures/property_change_notifier#mixin-compilation-error
