### ISSUE TITLE
    assert(listener is VoidCallback || listener is PropertyCallback<T>, 'Listener must be a Function() or Function(T)');

### ISSUE THREAD

**Issue by jordanhart** [VGVentures/property_change_notifier#11]
Hi! I am trying to pass in the listener 

```
 this.model.addListener(_listener, ["distanceFace"]);
  
void _listener(double newDistance) {
      print("$newDistance");
}
```
But am hitting this error
    assert(listener is VoidCallback || listener is PropertyCallback<T>, 'Listener must be a Function() or Function(T)');

The listener seems to be a function with a single parameter. Any suggestions or advice on why this may be occurring?

Thank you!
Joran

**Comment by martinrybak** [comment]
Hi Joran, listeners are provided the _name_ of the property that changed, not the value itself.
