### ISSUE TITLE
Rebuilding from PropertyChangeProvider even with "listen: false"

### ISSUE THREAD

**Issue by eliseyOzerov** [VGVentures/property_change_notifier#13]
Hi,

My problem is that when I access my model via `PropertyChangeProvider.of<MapController>(context, listen: false).value`, the widget rebuilds itself once a value inside `MapController` has changed. If I access the model via `Provider.of<MapController>(context, listen: false)`, this doesn't happen. I update the model with `notifyListeners('googleMapMarkers')`.

**Comment by martinrybak** [comment]
Hm that sounds super strange since `.value` is just a getter for the model. Are you sure something else is not causing the rebuild? Please provide a full example that demonstrates the issue, thanks!
