### ISSUE TITLE
Try to add a custom class PropertyChangeNotifier

### ISSUE THREAD

**Issue by maxime-aubry** [VGVentures/property_change_notifier#14]
Hello.

I try to add my custom class PropertyChangeNotifier.
Here is the code :
```
import 'package:flutter/foundation.dart';
import 'package:property_change_notifier/property_change_notifier.dart';

class ModelForm extends PropertyChangeNotifier<String> {
  @override
  @protected
  @visibleForTesting
  bool get hasListeners {
    return super.hasListeners;
  }

  @override
  void addListener(Function listener, [Iterable<String> properties]) =>
      super.addListener(listener, properties);

  @override
  void removeListener(Function listener, [Iterable<String> properties]) =>
      super.removeListener(listener, properties);

  @override
  @mustCallSuper
  void dispose() => super.dispose();

  @override
  @protected
  @visibleForTesting
  void notifyListeners([String property]) {
    /*********************************
     * CUSTOM CODE HERE
     ********************************/
    super.notifyListeners(property);
  }
}
```

I get an error when I start my project :
`NoSuchMethodError: Super class of class 'ComplexFormTest' has no instance method 'notifyListeners' with matching arguments.
Receiver: Instance of 'ComplexFormTest'
Tried calling: super.notifyListeners("128834879.books")
Found: super.notifyListeners([String]) => void`

What can I do ?
Thnaks.

**Comment by martinrybak** [comment]
Hi, I tried your code on my end and it works fine. FYI your error message says `ComplexFormTest` but the example you provided says `ModelForm`. Maybe different code is causing the problem?
