### ISSUE TITLE
ancestorWidgetOfExactType'isn't defined for the class 'BuildContext'

### ISSUE THREAD

**Issue by Navneetsinh53** [VGVentures/property_change_notifier#18]
While using this plugin with Flutter version 2.0.0 getting this run time error.
I would like to know when the new update will be available?

**Comment by JordanRoberts1** [comment]
@Navneetsinh53 did you ever solve this issue? I am having the same problem and have yet to work around it

**Comment by Navneetsinh53** [comment]
@JordanRoberts1 A temporary solution for this issue is 
In “property_change_provider.dart” file replace “ancestorWidgetOfExactType(type)” with  “findAncestorWidgetOfExactType()”.

**Note :** As per my last email discussion with the plugin author(@martinrybak), he will provide an update for this plugin.

**Comment by skast96** [comment]
Are there any plans for updating this repo? It seems pretty useful to me.

**Comment by martinrybak** [comment]
https://pub.dev/packages/property_change_notifier/versions/0.3.0
