### ISSUE TITLE
How can I update some properties (not all) at the same time?

### ISSUE THREAD

**Issue by anlam87** [VGVentures/property_change_notifier#4]
In the example, I can update foo by calling ```notifyListeners('foo');```, or update all foo and bar at the same time by calling ```notifyListeners()``` and remove properties ```properties: []``` in the widget. But I can't update 2 of 3 properties at the same time. For example, I have 3 properties: foo, bar, baz. I want to update only foo and bar at the same time, don't update baz. How can I do that?

**Comment by martinrybak** [comment]
You can listen to any number of properties in your widget: `properties: ['foo', 'bar']`

**Comment by martinrybak** [comment]
Please reopen if this does not solve your problem.

**Comment by anlam87** [comment]
If you use `properties: ['foo', 'bar']`, it will rebuild widget 2 times when you call `notifyListeners('foo');` `and notifyListeners('bar');` I want it's called only one time.

However, I can handle it by using another key, for example: 
```
_foo++;
_bar++;
notifyListeners('foobar');
```
And use: `properties: ['foobar']` to listen to the change and get the value of foo and bar at only one time.
Many thanks for your library.

**Comment by martinrybak** [comment]
Nice! You can absolutely use "fake" properties.
