### ISSUE TITLE
Type inference

### ISSUE THREAD

**Issue by befora** [VGVentures/property_change_notifier#6]
Does not work:
`MyNotifier get myNotifier => PropertyChangeProvider.of(context).value;`

Does work:
`MyNotifier get myNotifier => PropertyChangeProvider.of<MyNotifier>(context).value;`

Is it possible to return `T` (type) so type interference will work?

Thank you for sharing this package, I'm just tinkering around and it is solving some real issues.

**Comment by befora** [comment]
log

```
Could not find an ancestor PropertyChangeProvider<PropertyChangeNotifier<Object>>
'package:property_change_notifier/src/property_change_provider.dart':
Failed assertion: line 43 pos 14: 'model != null'
```

**Comment by martinrybak** [comment]
I'm sorry, this is not possible. The generic type is used at runtime.

**Comment by befora** [comment]
No big deal, thanks for the response.
